library(tidyverse)
library(sf)
library(grid)

#DC schools wrangling - 3/5/2020

#*******************
#data wrangling i did to create a table of schools and the two variables we want
#*******************

#dir <- read.csv("C:/Users/kennethsteif/Desktop/Spring_2020/z_trash/dcSchools/schoolsDirectory.csv")
#starGrade <- read.csv("C:/Users/kennethsteif/Desktop/Spring_2020/z_trash/dcSchools/starsFramework.csv")
#starScores <- read.csv("C:/Users/kennethsteif/Desktop/Spring_2020/z_trash/dcSchools/starsScores.csv")

# 
# dir.grade <-
#   left_join(dir, starGrade, by = c( "School.Code")) %>%
#   mutate(GIS_ID = paste0("dcps_",School.Code)) %>%
#   select(School.Code, School.Name.x, Framework.STAR.Rating, Framework.STAR.Score,GIS_ID)

#dput(dir.grade)

#*********************
#I've just dput the table of school data here - more wranling after
#*********************

starData <- 
  structure(list(School.Code = c(202L, 203L, 450L, 452L, 462L, 
                                 204L, 1058L, 205L, 206L, 402L, 212L, 213L, 213L, 347L, 404L, 
                                 404L, 296L, 219L, 220L, 221L, 247L, 360L, 360L, 454L, 454L, 224L, 
                                 442L, 442L, 455L, 405L, 349L, 231L, 471L, 467L, 457L, 232L, 407L, 
                                 318L, 318L, 238L, 239L, 227L, 464L, 246L, 413L, 258L, 249L, 251L, 
                                 252L, 1071L, 339L, 254L, 433L, 416L, 421L, 257L, 272L, 259L, 
                                 344L, 417L, 264L, 264L, 261L, 262L, 370L, 291L, 266L, 266L, 271L, 
                                 884L, 420L, 308L, 273L, 284L, 274L, 435L, 458L, 280L, 285L, 287L, 
                                 288L, 290L, 292L, 292L, 294L, 295L, 301L, 478L, 299L, 300L, 316L, 
                                 302L, 302L, 304L, 436L, 459L, 456L, 305L, 307L, 409L, 409L, 466L, 
                                 175L, 309L, 313L, 315L, 322L, 427L, 319L, 321L, 428L, 324L, 324L, 
                                 325L, 326L, 327L, 327L, 328L, 329L, 330L, 331L, 332L, 332L, 474L, 
                                 333L, 336L, 336L, 335L, 335L, 338L, 338L, 463L, 140L, 3072L, 
                                 3073L, 1137L, 1069L, 142L, 1207L, 184L, 182L, 109L, 102L, 199L, 
                                 276L, 1110L, 218L, 218L, 130L, 196L, 196L, 1206L, 1138L, 146L, 
                                 195L, 1125L, 138L, 126L, 269L, 1140L, 361L, 362L, 362L, 363L, 
                                 364L, 364L, 186L, 1083L, 1084L, 268L, 268L, 113L, 1057L, 1164L, 
                                 1124L, 365L, 366L, 366L, 131L, 114L, 114L, 188L, 115L, 161L, 
                                 161L, 163L, 116L, 236L, 1123L, 209L, 1122L, 1129L, 3071L, 1085L, 
                                 189L, 132L, 190L, 242L, 1121L, 237L, 1086L, 214L, 243L, 121L, 
                                 193L, 128L, 135L, 135L, 101L, 137L, 165L, 165L, 222L, 170L, 173L, 
                                 174L, 174L, 1047L, 159L, 1059L, 168L, 191L, 198L, 198L, 270L, 
                                 125L, 1118L, 217L, 1100L, 1100L, 1103L, 1103L, 1104L, 1104L, 
                                 1105L, 1105L, 1106L, 1106L, 1107L, 1107L, 1108L, 1108L, 1117L, 
                                 1119L, 1120L, 3064L, 3064L, 3066L, 3067L, 3068L, 3068L, 3069L, 
                                 3069L, 3070L, 3070L, 3065L, 1088L, 104L, 200L, 197L, 216L, 228L, 
                                 1141L, 233L, 245L, 248L, 248L, 260L, 263L, 267L, 255L, 289L, 
                                 297L, 1016L, 286L, 283L, 1036L, 1037L, 1038L), School.Name.x = structure(c(4L, 
                                                                                                            5L, 6L, 12L, 13L, 14L, 15L, 16L, 18L, 19L, 21L, 23L, 23L, 25L, 
                                                                                                            26L, 26L, 27L, 28L, 29L, 30L, 31L, 35L, 35L, 36L, 36L, 47L, 48L, 
                                                                                                            48L, 50L, 59L, 62L, 63L, 64L, 65L, 72L, 73L, 74L, 77L, 77L, 94L, 
                                                                                                            95L, 97L, 98L, 99L, 101L, 102L, 103L, 106L, 108L, 109L, 113L, 
                                                                                                            114L, 115L, 116L, 117L, 118L, 119L, 120L, 121L, 141L, 145L, 145L, 
                                                                                                            142L, 143L, 144L, 147L, 149L, 149L, 152L, 153L, 154L, 155L, 156L, 
                                                                                                            157L, 159L, 162L, 163L, 165L, 167L, 170L, 171L, 173L, 174L, 174L, 
                                                                                                            175L, 178L, 179L, 181L, 182L, 183L, 184L, 185L, 185L, 187L, 190L, 
                                                                                                            191L, 192L, 194L, 195L, 197L, 197L, 198L, 196L, 199L, 202L, 204L, 
                                                                                                            205L, 206L, 208L, 210L, 211L, 212L, 212L, 216L, 217L, 219L, 219L, 
                                                                                                            220L, 221L, 224L, 225L, 226L, 226L, 231L, 233L, 234L, 234L, 235L, 
                                                                                                            235L, 236L, 236L, 237L, 7L, 8L, 9L, 10L, 11L, 22L, 32L, 33L, 
                                                                                                            34L, 45L, 46L, 52L, 53L, 54L, 55L, 55L, 56L, 57L, 57L, 66L, 67L, 
                                                                                                            68L, 69L, 70L, 71L, 24L, 78L, 79L, 80L, 81L, 81L, 82L, 83L, 83L, 
                                                                                                            84L, 85L, 86L, 87L, 87L, 88L, 89L, 90L, 91L, 92L, 93L, 93L, 104L, 
                                                                                                            105L, 105L, 38L, 107L, 180L, 180L, 110L, 123L, 124L, 125L, 126L, 
                                                                                                            127L, 128L, 129L, 130L, 131L, 133L, 132L, 134L, 135L, 136L, 137L, 
                                                                                                            138L, 139L, 140L, 146L, 238L, 158L, 158L, 160L, 161L, 164L, 164L, 
                                                                                                            176L, 177L, 193L, 200L, 200L, 207L, 75L, 76L, 215L, 218L, 222L, 
                                                                                                            222L, 223L, 228L, 229L, 2L, 3L, 3L, 39L, 39L, 40L, 40L, 41L, 
                                                                                                            41L, 42L, 42L, 43L, 43L, 44L, 44L, 232L, 37L, 172L, 112L, 112L, 
                                                                                                            203L, 186L, 17L, 17L, 51L, 51L, 58L, 58L, 168L, 169L, 148L, 111L, 
                                                                                                            201L, 49L, 150L, 151L, 1L, 100L, 61L, 61L, 166L, 227L, 122L, 
                                                                                                            213L, 20L, 96L, 188L, 189L, 230L, 214L, 209L, 60L), .Label = c("Academy of Hope Adult PCS", 
                                                                                                                                                                           "Achievement Preparatory Academy PCS - Wahler Place Elementary School", 
                                                                                                                                                                           "Achievement Preparatory Academy PCS - Wahler Place Middle School", 
                                                                                                                                                                           "Aiton Elementary School", "Amidon-Bowen Elementary School", 
                                                                                                                                                                           "Anacostia High School", "AppleTree Early Learning Center PCS - Columbia Heights", 
                                                                                                                                                                           "AppleTree Early Learning Center PCS - Douglas Knoll", "AppleTree Early Learning Center PCS - Lincoln Park", 
                                                                                                                                                                           "AppleTree Early Learning Center PCS - Oklahoma Avenue", "AppleTree Early Learning Center PCS - Parklands at THEARC", 
                                                                                                                                                                           "Ballou High School", "Ballou STAY High School", "Bancroft Elementary School", 
                                                                                                                                                                           "Bard High School Early College DC", "Barnard Elementary School", 
                                                                                                                                                                           "BASIS DC PCS", "Beers Elementary School", "Benjamin Banneker High School", 
                                                                                                                                                                           "Breakthrough Montessori PCS", "Brent Elementary School", "Bridges PCS", 
                                                                                                                                                                           "Brightwood Education Campus", "Briya PCS", "Brookland Middle School", 
                                                                                                                                                                           "Browne Education Campus", "Bruce-Monroe Elementary School @ Park View", 
                                                                                                                                                                           "Bunker Hill Elementary School", "Burroughs Elementary School", 
                                                                                                                                                                           "Burrville Elementary School", "C.W. Harris Elementary School", 
                                                                                                                                                                           "Capital City PCS - High School", "Capital City PCS - Lower School", 
                                                                                                                                                                           "Capital City PCS - Middle School", "Capitol Hill Montessori School @ Logan", 
                                                                                                                                                                           "Cardozo Education Campus", "Carlos Rosario International PCS", 
                                                                                                                                                                           "Cedar Tree Academy PCS", "Center City PCS - Brightwood", "Center City PCS - Capitol Hill", 
                                                                                                                                                                           "Center City PCS - Congress Heights", "Center City PCS - Petworth", 
                                                                                                                                                                           "Center City PCS - Shaw", "Center City PCS - Trinidad", "Cesar Chavez PCS for Public Policy - Parkside High School", 
                                                                                                                                                                           "Cesar Chavez PCS for Public Policy - Parkside Middle School", 
                                                                                                                                                                           "Cleveland Elementary School", "Columbia Heights Education Campus", 
                                                                                                                                                                           "Community College Preparatory Academy PCS", "Coolidge High School", 
                                                                                                                                                                           "Creative Minds International PCS", "DC Bilingual PCS", "DC Prep PCS - Anacostia Elementary School", 
                                                                                                                                                                           "DC Prep PCS - Benning Elementary School", "DC Prep PCS - Benning Middle School", 
                                                                                                                                                                           "DC Prep PCS - Edgewood Elementary School", "DC Prep PCS - Edgewood Middle School", 
                                                                                                                                                                           "DC Scholars PCS", "Deal Middle School", "Digital Pioneers Academy PCS", 
                                                                                                                                                                           "District of Columbia International School", "Dorothy I. Height Elementary School", 
                                                                                                                                                                           "Drew Elementary School", "Duke Ellington School of the Arts", 
                                                                                                                                                                           "Dunbar High School", "E.L. Haynes PCS - Elementary School", 
                                                                                                                                                                           "E.L. Haynes PCS - High School", "E.L. Haynes PCS - Middle School", 
                                                                                                                                                                           "Eagle Academy PCS - Congress Heights", "Eagle Academy PCS - Fairlawn", 
                                                                                                                                                                           "Early Childhood Academy PCS", "Eastern High School", "Eaton Elementary School", 
                                                                                                                                                                           "Eliot-Hine Middle School", "Elsie Whitlow Stokes Community Freedom PCS - Brookland", 
                                                                                                                                                                           "Elsie Whitlow Stokes Community Freedom PCS - East End", "Excel Academy", 
                                                                                                                                                                           "Friendship PCS - Armstrong Elementary", "Friendship PCS - Armstrong Middle", 
                                                                                                                                                                           "Friendship PCS - Blow Pierce Elementary School", "Friendship PCS - Blow Pierce Middle School", 
                                                                                                                                                                           "Friendship PCS - Chamberlain Elementary School", "Friendship PCS - Chamberlain Middle School", 
                                                                                                                                                                           "Friendship PCS - Collegiate Academy", "Friendship PCS - Ideal Elementary", 
                                                                                                                                                                           "Friendship PCS - Ideal Middle School", "Friendship PCS - Online", 
                                                                                                                                                                           "Friendship PCS - Southeast Elementary School", "Friendship PCS - Southeast Middle School", 
                                                                                                                                                                           "Friendship PCS - Technology Preparatory High School", "Friendship PCS - Technology Preparatory Middle School", 
                                                                                                                                                                           "Friendship PCS - Woodridge Elementary School", "Friendship PCS - Woodridge Middle School", 
                                                                                                                                                                           "Garfield Elementary School", "Garrison Elementary School", "Goodwill Excel Center PCS", 
                                                                                                                                                                           "H.D. Cooke Elementary School", "H.D. Woodson High School", "Hardy Middle School", 
                                                                                                                                                                           "Harmony DC PCS - School of Excellence", "Hart Middle School", 
                                                                                                                                                                           "Hearst Elementary School", "Hendley Elementary School", "Hope Community PCS - Lamond", 
                                                                                                                                                                           "Hope Community PCS - Tolson", "Houston Elementary School", "Howard University Middle School of Mathematics and Science PCS", 
                                                                                                                                                                           "Hyde-Addison Elementary School", "Ida B. Wells Middle School", 
                                                                                                                                                                           "IDEA PCS", "Ingenuity Prep PCS", "Inspired Teaching Demonstration PCS", 
                                                                                                                                                                           "J.O. Wilson Elementary School", "Janney Elementary School", 
                                                                                                                                                                           "Jefferson Middle School Academy", "Johnson Middle School", "Kelly Miller Middle School", 
                                                                                                                                                                           "Ketcham Elementary School", "Key Elementary School", "Kimball Elementary School", 
                                                                                                                                                                           "King Elementary School", "Kingsman Academy PCS", "KIPP DC - AIM Academy PCS", 
                                                                                                                                                                           "KIPP DC - Arts and Technology Academy PCS", "KIPP DC - College Preparatory Academy PCS", 
                                                                                                                                                                           "KIPP DC - Connect Academy PCS", "KIPP DC - Discover Academy PCS", 
                                                                                                                                                                           "KIPP DC - Grow Academy PCS", "KIPP DC - Heights Academy PCS", 
                                                                                                                                                                           "KIPP DC - Honor Academy PCS", "KIPP DC - KEY Academy PCS", "KIPP DC - Lead Academy PCS", 
                                                                                                                                                                           "KIPP DC - LEAP Academy PCS", "KIPP DC - Northeast Academy PCS", 
                                                                                                                                                                           "KIPP DC - Promise Academy PCS", "KIPP DC - Quest Academy PCS", 
                                                                                                                                                                           "KIPP DC - Somerset College Preparatory PCS", "KIPP DC - Spring Academy PCS", 
                                                                                                                                                                           "KIPP DC - Valor Academy PCS", "KIPP DC - WILL Academy PCS", 
                                                                                                                                                                           "Kramer Middle School", "Lafayette Elementary School", "Langdon Elementary School", 
                                                                                                                                                                           "Langley Elementary School", "LaSalle-Backus Education Campus", 
                                                                                                                                                                           "Latin American Montessori Bilingual PCS", "Lawrence E. Boone Elementary School", 
                                                                                                                                                                           "LAYC Career Academy PCS", "Leckie Education Campus", "Lee Montessori PCS - Brookland", 
                                                                                                                                                                           "Lee Montessori PCS - East End", "Ludlow-Taylor Elementary School", 
                                                                                                                                                                           "Luke C. Moore High School", "MacFarland Middle School", "Malcolm X Elementary School @ Green", 
                                                                                                                                                                           "Mann Elementary School", "Marie Reed Elementary School", "Mary McLeod Bethune Day Academy PCS", 
                                                                                                                                                                           "Maury Elementary School", "Maya Angelou PCS - High School", 
                                                                                                                                                                           "Maya Angelou PCS - Young Adult Learning Center", "McKinley Middle School", 
                                                                                                                                                                           "McKinley Technology High School", "Meridian PCS", "Miner Elementary School", 
                                                                                                                                                                           "Monument Academy PCS", "Moten Elementary School", "Mundo Verde Bilingual PCS", 
                                                                                                                                                                           "Mundo Verde Bilingual PCS - 4401 8th Street NE Campus", "Murch Elementary School", 
                                                                                                                                                                           "Nalle Elementary School", "National Collegiate Preparatory PCHS", 
                                                                                                                                                                           "Noyes Elementary School", "Oyster-Adams Bilingual School", "Patterson Elementary School", 
                                                                                                                                                                           "Paul PCS - International High School", "Paul PCS - Middle School", 
                                                                                                                                                                           "Payne Elementary School", "Peabody Elementary School (Capitol Hill Cluster)", 
                                                                                                                                                                           "Perry Street Preparatory PCS", "Phelps Architecture, Construction and Engineering High School", 
                                                                                                                                                                           "Plummer Elementary School", "Powell Elementary School", "Randle Highlands Elementary School", 
                                                                                                                                                                           "Raymond Education Campus", "Richard Wright PCS for Journalism and Media Arts", 
                                                                                                                                                                           "River Terrace Education Campus", "Rocketship DC PCS - Legacy Prep", 
                                                                                                                                                                           "Rocketship DC PCS - Rise Academy", "Ron Brown College Preparatory High School", 
                                                                                                                                                                           "Roosevelt High School", "Roosevelt STAY High School", "Roots PCS", 
                                                                                                                                                                           "Ross Elementary School", "Savoy Elementary School", "School-Within-School @ Goding", 
                                                                                                                                                                           "School Without Walls @ Francis-Stevens", "School Without Walls High School", 
                                                                                                                                                                           "Seaton Elementary School", "SEED PCS of Washington DC", "Sela PCS", 
                                                                                                                                                                           "Shepherd Elementary School", "Shining Stars Montessori Academy PCS", 
                                                                                                                                                                           "Simon Elementary School", "Smothers Elementary School", "Sousa Middle School", 
                                                                                                                                                                           "St. Coletta Special Education PCS", "Stanton Elementary School", 
                                                                                                                                                                           "Statesmen College Preparatory Academy for Boys PCS", "Stoddert Elementary School", 
                                                                                                                                                                           "Stuart-Hobson Middle School (Capitol Hill Cluster)", "Takoma Education Campus", 
                                                                                                                                                                           "The Children's Guild PCS", "The Family Place PCS", "The Next Step El Proximo Paso PCS", 
                                                                                                                                                                           "Thomas Elementary School", "Thomson Elementary School", "Thurgood Marshall Academy PCS", 
                                                                                                                                                                           "Truesdell Education Campus", "Tubman Elementary School", "Turner Elementary School", 
                                                                                                                                                                           "Two Rivers PCS - 4th St", "Two Rivers PCS - Young", "Tyler Elementary School", 
                                                                                                                                                                           "Van Ness Elementary School", "Walker-Jones Education Campus", 
                                                                                                                                                                           "Washington Global PCS", "Washington Latin PCS - Middle School", 
                                                                                                                                                                           "Washington Latin PCS - Upper School", "Washington Leadership Academy PCS", 
                                                                                                                                                                           "Washington Metropolitan High School", "Washington Yu Ying PCS", 
                                                                                                                                                                           "Watkins Elementary School (Capitol Hill Cluster)", "West Education Campus", 
                                                                                                                                                                           "Wheatley Education Campus", "Whittier Education Campus", "Woodrow Wilson High School", 
                                                                                                                                                                           "Youthbuild PCS"), class = "factor"), Framework.STAR.Rating = c(1L, 
                                                                                                                                                                                                                                           3L, 1L, 1L, NA, 5L, NA, 4L, 2L, 5L, 5L, 4L, 3L, 3L, 2L, 2L, 4L, 
                                                                                                                                                                                                                                           2L, 4L, 4L, 2L, 4L, 4L, 1L, 1L, 3L, 3L, 4L, 1L, 5L, 4L, 2L, 4L, 
                                                                                                                                                                                                                                           2L, 2L, 4L, 2L, 2L, 3L, 2L, 4L, 3L, 1L, 5L, 3L, 4L, 2L, 2L, 4L, 
                                                                                                                                                                                                                                           NA, 3L, 5L, 3L, 2L, 2L, 3L, 4L, 4L, 2L, 1L, 4L, 4L, 5L, 4L, 2L, 
                                                                                                                                                                                                                                           3L, 2L, 3L, 3L, NA, 2L, 3L, 5L, 4L, 5L, 1L, 5L, 2L, 1L, 5L, 3L, 
                                                                                                                                                                                                                                           2L, 4L, 5L, 1L, 4L, NA, 3L, 3L, 4L, 3L, 3L, 4L, NA, 1L, 1L, 1L, 
                                                                                                                                                                                                                                           4L, 3L, 3L, 4L, 5L, 5L, 4L, 4L, 1L, 1L, 2L, 2L, 4L, 4L, 3L, 3L, 
                                                                                                                                                                                                                                           2L, 4L, 4L, 4L, 2L, 2L, 4L, 4L, 2L, 2L, 1L, 4L, 4L, 5L, 2L, 3L, 
                                                                                                                                                                                                                                           4L, 5L, 4L, NA, NA, NA, NA, NA, 3L, 3L, 3L, 4L, 2L, 2L, 4L, NA, 
                                                                                                                                                                                                                                           4L, 2L, 5L, 4L, 3L, 5L, 4L, 3L, 3L, 2L, 3L, 2L, NA, 2L, NA, 2L, 
                                                                                                                                                                                                                                           1L, 4L, 3L, 2L, 3L, 3L, NA, NA, 3L, 4L, 3L, 2L, 4L, 3L, 4L, 4L, 
                                                                                                                                                                                                                                           5L, 3L, 2L, 3L, NA, 2L, 3L, 4L, 3L, 4L, NA, 4L, NA, NA, NA, 3L, 
                                                                                                                                                                                                                                           NA, 3L, NA, 3L, 2L, 5L, 4L, NA, 3L, 3L, 4L, 4L, NA, 2L, 3L, 3L, 
                                                                                                                                                                                                                                           NA, 2L, 3L, 3L, 3L, 2L, 3L, 2L, NA, 3L, NA, NA, 4L, 4L, 4L, 3L, 
                                                                                                                                                                                                                                           4L, 5L, 1L, 1L, 2L, 4L, 5L, 2L, 2L, 5L, 5L, 3L, 3L, 3L, 3L, 2L, 
                                                                                                                                                                                                                                           2L, 5L, NA, 2L, 4L, 4L, 2L, 3L, 5L, 4L, 3L, 3L, 2L, 3L, 4L, NA, 
                                                                                                                                                                                                                                           NA, 3L, 4L, NA, 4L, NA, NA, 2L, 5L, 4L, 2L, 3L, 2L, 2L, NA, NA, 
                                                                                                                                                                                                                                           3L, 3L, 4L, NA, 2L, 3L), Framework.STAR.Score = c(11L, 49L, 4L, 
                                                                                                                                                                                                                                                                                             5L, NA, 83L, NA, 73L, 39L, 99L, 81L, 65L, 47L, 41L, 21L, 39L, 
                                                                                                                                                                                                                                                                                             69L, 35L, 62L, 61L, 22L, 62L, 70L, 15L, 19L, 49L, 52L, 66L, 15L, 
                                                                                                                                                                                                                                                                                             89L, 60L, 20L, 74L, 22L, 25L, 73L, 31L, 31L, 60L, 22L, 78L, 53L, 
                                                                                                                                                                                                                                                                                             18L, 90L, 44L, 67L, 36L, 26L, 61L, NA, 51L, 83L, 50L, 26L, 26L, 
                                                                                                                                                                                                                                                                                             42L, 77L, 60L, 35L, 2L, 64L, 64L, 82L, 66L, 32L, 47L, 23L, 50L, 
                                                                                                                                                                                                                                                                                             52L, NA, 31L, 42L, 86L, 68L, 83L, 19L, 87L, 25L, 20L, 92L, 55L, 
                                                                                                                                                                                                                                                                                             30L, 71L, 84L, 17L, 72L, NA, 54L, 44L, 62L, 49L, 59L, 75L, NA, 
                                                                                                                                                                                                                                                                                             15L, 13L, 17L, 70L, 40L, 54L, 62L, 98L, 88L, 71L, 77L, 18L, 16L, 
                                                                                                                                                                                                                                                                                             32L, 39L, 78L, 61L, 44L, 46L, 33L, 61L, 61L, 79L, 37L, 32L, 75L, 
                                                                                                                                                                                                                                                                                             67L, 28L, 25L, 13L, 70L, 63L, 87L, 22L, 40L, 65L, 92L, 72L, NA, 
                                                                                                                                                                                                                                                                                             NA, NA, NA, NA, 40L, 56L, 41L, 62L, 40L, 38L, 80L, NA, 69L, 32L, 
                                                                                                                                                                                                                                                                                             89L, 68L, 57L, 95L, 68L, 53L, 49L, 32L, 47L, 29L, NA, 34L, NA, 
                                                                                                                                                                                                                                                                                             27L, 20L, 71L, 47L, 38L, 47L, 45L, NA, NA, 40L, 69L, 57L, 38L, 
                                                                                                                                                                                                                                                                                             63L, 47L, 71L, 64L, 87L, 41L, 36L, 53L, NA, 39L, 48L, 70L, 43L, 
                                                                                                                                                                                                                                                                                             61L, NA, 69L, NA, NA, NA, 59L, NA, 54L, NA, 47L, 34L, 84L, 65L, 
                                                                                                                                                                                                                                                                                             NA, 55L, 43L, 67L, 72L, NA, 36L, 49L, 57L, NA, 35L, 47L, 51L, 
                                                                                                                                                                                                                                                                                             51L, 34L, 55L, 35L, NA, 60L, NA, NA, 63L, 61L, 71L, 43L, 75L, 
                                                                                                                                                                                                                                                                                             89L, 15L, 10L, 33L, 60L, 96L, 29L, 39L, 80L, 81L, 42L, 52L, 43L, 
                                                                                                                                                                                                                                                                                             44L, 38L, 32L, 87L, NA, 28L, 63L, 62L, 25L, 46L, 98L, 78L, 59L, 
                                                                                                                                                                                                                                                                                             54L, 29L, 42L, 69L, NA, NA, 50L, 66L, NA, 60L, NA, NA, 33L, 83L, 
                                                                                                                                                                                                                                                                                             66L, 28L, 56L, 34L, 30L, NA, NA, 58L, 51L, 63L, NA, 37L, 50L), 
                 GIS_ID = c("dcps_202", "dcps_203", "dcps_450", "dcps_452", 
                            "dcps_462", "dcps_204", "dcps_1058", "dcps_205", "dcps_206", 
                            "dcps_402", "dcps_212", "dcps_213", "dcps_213", "dcps_347", 
                            "dcps_404", "dcps_404", "dcps_296", "dcps_219", "dcps_220", 
                            "dcps_221", "dcps_247", "dcps_360", "dcps_360", "dcps_454", 
                            "dcps_454", "dcps_224", "dcps_442", "dcps_442", "dcps_455", 
                            "dcps_405", "dcps_349", "dcps_231", "dcps_471", "dcps_467", 
                            "dcps_457", "dcps_232", "dcps_407", "dcps_318", "dcps_318", 
                            "dcps_238", "dcps_239", "dcps_227", "dcps_464", "dcps_246", 
                            "dcps_413", "dcps_258", "dcps_249", "dcps_251", "dcps_252", 
                            "dcps_1071", "dcps_339", "dcps_254", "dcps_433", "dcps_416", 
                            "dcps_421", "dcps_257", "dcps_272", "dcps_259", "dcps_344", 
                            "dcps_417", "dcps_264", "dcps_264", "dcps_261", "dcps_262", 
                            "dcps_370", "dcps_291", "dcps_266", "dcps_266", "dcps_271", 
                            "dcps_884", "dcps_420", "dcps_308", "dcps_273", "dcps_284", 
                            "dcps_274", "dcps_435", "dcps_458", "dcps_280", "dcps_285", 
                            "dcps_287", "dcps_288", "dcps_290", "dcps_292", "dcps_292", 
                            "dcps_294", "dcps_295", "dcps_301", "dcps_478", "dcps_299", 
                            "dcps_300", "dcps_316", "dcps_302", "dcps_302", "dcps_304", 
                            "dcps_436", "dcps_459", "dcps_456", "dcps_305", "dcps_307", 
                            "dcps_409", "dcps_409", "dcps_466", "dcps_175", "dcps_309", 
                            "dcps_313", "dcps_315", "dcps_322", "dcps_427", "dcps_319", 
                            "dcps_321", "dcps_428", "dcps_324", "dcps_324", "dcps_325", 
                            "dcps_326", "dcps_327", "dcps_327", "dcps_328", "dcps_329", 
                            "dcps_330", "dcps_331", "dcps_332", "dcps_332", "dcps_474", 
                            "dcps_333", "dcps_336", "dcps_336", "dcps_335", "dcps_335", 
                            "dcps_338", "dcps_338", "dcps_463", "dcps_140", "dcps_3072", 
                            "dcps_3073", "dcps_1137", "dcps_1069", "dcps_142", "dcps_1207", 
                            "dcps_184", "dcps_182", "dcps_109", "dcps_102", "dcps_199", 
                            "dcps_276", "dcps_1110", "dcps_218", "dcps_218", "dcps_130", 
                            "dcps_196", "dcps_196", "dcps_1206", "dcps_1138", "dcps_146", 
                            "dcps_195", "dcps_1125", "dcps_138", "dcps_126", "dcps_269", 
                            "dcps_1140", "dcps_361", "dcps_362", "dcps_362", "dcps_363", 
                            "dcps_364", "dcps_364", "dcps_186", "dcps_1083", "dcps_1084", 
                            "dcps_268", "dcps_268", "dcps_113", "dcps_1057", "dcps_1164", 
                            "dcps_1124", "dcps_365", "dcps_366", "dcps_366", "dcps_131", 
                            "dcps_114", "dcps_114", "dcps_188", "dcps_115", "dcps_161", 
                            "dcps_161", "dcps_163", "dcps_116", "dcps_236", "dcps_1123", 
                            "dcps_209", "dcps_1122", "dcps_1129", "dcps_3071", "dcps_1085", 
                            "dcps_189", "dcps_132", "dcps_190", "dcps_242", "dcps_1121", 
                            "dcps_237", "dcps_1086", "dcps_214", "dcps_243", "dcps_121", 
                            "dcps_193", "dcps_128", "dcps_135", "dcps_135", "dcps_101", 
                            "dcps_137", "dcps_165", "dcps_165", "dcps_222", "dcps_170", 
                            "dcps_173", "dcps_174", "dcps_174", "dcps_1047", "dcps_159", 
                            "dcps_1059", "dcps_168", "dcps_191", "dcps_198", "dcps_198", 
                            "dcps_270", "dcps_125", "dcps_1118", "dcps_217", "dcps_1100", 
                            "dcps_1100", "dcps_1103", "dcps_1103", "dcps_1104", "dcps_1104", 
                            "dcps_1105", "dcps_1105", "dcps_1106", "dcps_1106", "dcps_1107", 
                            "dcps_1107", "dcps_1108", "dcps_1108", "dcps_1117", "dcps_1119", 
                            "dcps_1120", "dcps_3064", "dcps_3064", "dcps_3066", "dcps_3067", 
                            "dcps_3068", "dcps_3068", "dcps_3069", "dcps_3069", "dcps_3070", 
                            "dcps_3070", "dcps_3065", "dcps_1088", "dcps_104", "dcps_200", 
                            "dcps_197", "dcps_216", "dcps_228", "dcps_1141", "dcps_233", 
                            "dcps_245", "dcps_248", "dcps_248", "dcps_260", "dcps_263", 
                            "dcps_267", "dcps_255", "dcps_289", "dcps_297", "dcps_1016", 
                            "dcps_286", "dcps_283", "dcps_1036", "dcps_1037", "dcps_1038"
                 ), Accountability.Framework = structure(c(2L, 2L, 4L, 4L, 
                                                           NA, 2L, NA, 2L, 2L, 4L, 2L, 2L, 5L, 5L, 2L, 5L, 2L, 2L, 2L, 
                                                           2L, 2L, 2L, 5L, 4L, 5L, 2L, 4L, 5L, 4L, 5L, 2L, 2L, 4L, 4L, 
                                                           4L, 2L, 5L, 2L, 5L, 2L, 2L, 2L, 4L, 5L, 5L, 2L, 2L, 2L, 2L, 
                                                           NA, 2L, 2L, 5L, 5L, 5L, 2L, 2L, 2L, 2L, 5L, 2L, 5L, 2L, 2L, 
                                                           2L, 2L, 2L, 5L, 2L, NA, 5L, 2L, 2L, 2L, 2L, 5L, 4L, 2L, 2L, 
                                                           2L, 2L, 2L, 2L, 5L, 2L, 2L, NA, 4L, 2L, 2L, 2L, 2L, 5L, NA, 
                                                           4L, 4L, 1L, 2L, 2L, 2L, 5L, 4L, 2L, 2L, 2L, 2L, 2L, 5L, 2L, 
                                                           2L, 5L, 2L, 5L, 2L, 2L, 2L, 5L, 2L, 2L, 2L, 2L, 2L, 5L, 1L, 
                                                           3L, 2L, 5L, 2L, 5L, 2L, 5L, 4L, NA, NA, NA, NA, NA, 2L, 4L, 
                                                           2L, 5L, 4L, 5L, 2L, NA, 2L, 3L, 5L, 2L, 3L, 5L, 2L, 4L, 5L, 
                                                           2L, 2L, 2L, NA, 2L, NA, 2L, 3L, 5L, 2L, 3L, 5L, 4L, NA, NA, 
                                                           3L, 5L, 2L, 3L, 4L, 5L, 2L, 3L, 5L, 2L, 2L, 5L, NA, 5L, 2L, 
                                                           5L, 4L, 5L, NA, 4L, NA, NA, NA, 3L, NA, 5L, NA, 3L, 5L, 3L, 
                                                           3L, NA, 3L, 5L, 5L, 2L, NA, 2L, 5L, 1L, NA, 2L, 5L, 4L, 5L, 
                                                           2L, 4L, 5L, NA, 2L, NA, NA, 4L, 2L, 5L, 2L, 5L, 4L, 2L, 3L, 
                                                           5L, 2L, 5L, 2L, 5L, 2L, 5L, 2L, 5L, 2L, 5L, 2L, 5L, 2L, NA, 
                                                           4L, 2L, 5L, 2L, 4L, 4L, 5L, 2L, 5L, 2L, 5L, 2L, NA, NA, 2L, 
                                                           2L, NA, 2L, NA, NA, 3L, 4L, 5L, 1L, 5L, 1L, 1L, NA, NA, 2L, 
                                                           2L, 4L, NA, 3L, 5L), .Label = c("Alternative Framework", 
                                                                                           "Elementary School with Pre-Kindergarten", "Elementary School without Pre-Kindergarten", 
                                                                                           "High School", "Middle School"), class = "factor")), class = "data.frame", row.names = c(NA, 
                                                                                                                                                                                    -279L))